# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ccb99b56d7071165ea14e42dfb097ae9f99749479ef18046e802042b80d89e909d03ec76ac75fb6f369d4a1db96e981e50383aa2c8ebe6805567933c1caec9b

test:
  secret_key_base: 361e611b3e4bb578ba75fa0af2ddbb4a1dcf9813bbba992465eb2f00a26c0d424112269a414fad5b5f86824426b7991c8231f944ba131c67d10eb93f1d24fa98

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
